### ISSUE TITLE
Template list workflow runs on every forked repository

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/generator#921]
#### Describe the bug
Everyday github runs a workflow based on [templates-list-validator](https://github.com/asyncapi/generator/blob/master/.github/workflows/templates-list-validation.yml) .
The bug here is that this workflow runs on every forked repository also, which I think is not the aim of this workflow.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

- Screenshots
![image](https://user-images.githubusercontent.com/81870866/223930051-9d1da9ae-3a18-4dc8-9fa5-5f3ce71da362.png)

This issue can be resolved by adding an if statement which checks for only asyncapi repository.

**Comment by sambhavgupta0705** [comment]
@derberg can you please approve this issue.
Here cron jobs is doing work correctly,just an error here is that  it is running test on every forked repository also

**Comment by sambhavgupta0705** [comment]
```
jobs:
  templates:
    if: startsWith(github.repository, 'asyncapi/')
    name: 'Check list of templates'

```
Proposed solution for this

**Comment by derberg** [comment]
To be honest I think it is about time to probably remove the whole workflow and related custom action and instead, we should just make sure all templates are listed in https://www.asyncapi.com/tools 🤔

**Comment by derberg** [comment]
well we need to create 13 PRs in different repos to add `.asyncapi-tool` file there 😄 

- https://github.com/asyncapi/dotnet-rabbitmq-template
- https://github.com/asyncapi/dotnet-nats-template
- https://github.com/asyncapi/php-template
- https://github.com/asyncapi/java-template
- https://github.com/asyncapi/java-spring-template
- https://github.com/asyncapi/java-spring-cloud-stream-template
- https://github.com/asyncapi/ts-nats-template
- https://github.com/asyncapi/python-paho-template
- https://github.com/asyncapi/go-watermill-template
- https://github.com/asyncapi/nodejs-ws-template
- https://github.com/asyncapi/markdown-template
- https://github.com/asyncapi/nodejs-template
- https://github.com/asyncapi/html-template

example:
```yml
title: .NET RabbitMQ
filters:
    language: 'C#'
    technology:
        - AsyncAPI Generator
        - '.NET'
        - RabbitMQ
    categories:
        - code-generator
    hasCommercial: false
```

I'm only thinking that because there are so many AsyncAPI Generator templates, and more will come, that maybe we need a separate `category` for it. @akshatnema thoughts?

**Comment by sambhavgupta0705** [comment]
I would like to work on this one😀

**Comment by akshatnema** [comment]
> I'm only thinking that because there are so many AsyncAPI Generator templates, and more will come, that maybe we need a separate category for it.

Sorry, I didn't understand what you mean by separate category. Do you want to add any category inside categorylist?

> well we need to create 13 PRs in different repos to add .asyncapi-tool file there 

I will definitely say NO to this. Because currently,  you also know that Github API is not returning correct results to us via. Increasing this number of files increases the payload of the results of the API call, thus decreasing the probability of getting correct result in a script run. So, if you want to add any tool, please add it to tools-manual.json until we get a new version of GitHub Code search API.

**Comment by derberg** [comment]
> Sorry, I didn't understand what you mean by separate category. Do you want to add any category inside categorylist?

I mean that AsyncAPI Generator involves so many repositories/projects that it could also have own category, like `asyncapi-generator`
so one can say:
```
categories:
        - code-generator
        - asyncapi-generator
```

> tools-manual.json

oh, I definitely do not like this direction 😃

**Comment by akshatnema** [comment]
> oh, I definitely do not like this direction

Yeah, I too don't like this to add manual tools if we have the option of `.asyncapi-tool` file. But due to the payload of the API and incomplete results, we can't exceed the information extracted from the API.

**Comment by derberg** [comment]
But wasn't it working this way that on local you did not face any issues?

**Comment by sambhavgupta0705** [comment]
Hey @derberg what should we do with this one???

**Comment by AnimeshKumar923** [comment]
still valid? @sambhavgupta0705 @akshatnema @derberg

**Comment by sambhavgupta0705** [comment]
Yes it is
Still it runs the pr check on every forked repo

**Comment by lmgyuan** [comment]
The problematic workflow seems to be removed already. If anyone is having a same or similar issue, please make sure to update their fork master with latest upstream master. It should fix the issue.

**Comment by derberg** [comment]
we still don't have all the tools listed in https://www.asyncapi.com/tools#AsyncAPI%20Generator%20Templates

going with `.asyncapi-tool` in each repo no longer makes sense cause plans are eventually to pull templates into generator repo. I think best if someone finds time to manually add the templates that we have in readme by following this procedure https://github.com/asyncapi/community/blob/master/new-tool-documentation.md#manual-addition-of-tools

**Comment by Light13008** [comment]
actions needed on this issue are, 
1. **Stop using `.asyncapi-tool`** files, as they no longer align with future plans to consolidate templates into the generator repo.  
2. **Manually update the tools page** with missing templates by following this documented process: [[Manual Addition of Tools](https://github.com/asyncapi/community/blob/master/new-tool-documentation.md#manual-addition-of-tools)](https://github.com/asyncapi/community/blob/master/new-tool-documentation.md#manual-addition-of-tools).  

- Review the current list on the [[AsyncAPI Tools page](https://www.asyncapi.com/tools#AsyncAPI%20Generator%20Templates)](https://www.asyncapi.com/tools#AsyncAPI%20Generator%20Templates).
- Compare it with templates in the READMEs of repositories like [[dotnet-rabbitmq-template](https://github.com/asyncapi/dotnet-rabbitmq-template)](https://github.com/asyncapi/dotnet-rabbitmq-template), [[php-template](https://github.com/asyncapi/php-template)](https://github.com/asyncapi/php-template), and others.  
- Add any missing templates manually using the process linked above.

commenting here  for  **removing the stale tag** as this issue can still be worked upon and is essential for ensuring complete and accurate tool listings. 

any remarks @derberg and @ItshMoh

**Comment by derberg** [comment]
well, nothing to add, perfect overview, suggestions and action plans 👏🏼 

wanna work on this?
